# Generated by Django 5.2.11 on 2026-04-20 08:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def bootstrap_default_school(apps, schema_editor):
    School = apps.get_model('core', 'School')
    User = apps.get_model(*settings.AUTH_USER_MODEL.split('.'))
    UserProfile = apps.get_model('core', 'UserProfile')
    Student = apps.get_model('core', 'Student')
    Exam = apps.get_model('core', 'Exam')
    ExamSubject = apps.get_model('core', 'ExamSubject')
    SchoolSetting = apps.get_model('core', 'SchoolSetting')
    DocumentCounter = apps.get_model('core', 'DocumentCounter')

    default_school, _ = School.objects.get_or_create(
        name='Default School',
        defaults={'address': ''},
    )

    Student.objects.filter(school__isnull=True).update(school=default_school)
    Exam.objects.filter(school__isnull=True).update(school=default_school)
    ExamSubject.objects.filter(school__isnull=True).update(school=default_school)
    SchoolSetting.objects.filter(school__isnull=True).update(school=default_school)
    DocumentCounter.objects.filter(school__isnull=True).update(school=default_school)

    for user in User.objects.all():
        UserProfile.objects.get_or_create(user=user, defaults={'school': default_school})


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_student_gender'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='schools/logos/')),
                ('address', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'user profile',
                'verbose_name_plural': 'user profiles',
            },
        ),
        migrations.AlterField(
            model_name='student',
            name='admission_no',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='documentcounter',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='documentcounter',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_counters', to='core.school'),
        ),
        migrations.AddField(
            model_name='exam',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.school'),
        ),
        migrations.AddField(
            model_name='examsubject',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.school'),
        ),
        migrations.AddField(
            model_name='schoolsetting',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.school'),
        ),
        migrations.AddField(
            model_name='student',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.school'),
        ),
        migrations.AlterUniqueTogether(
            name='documentcounter',
            unique_together={('school', 'doc_type', 'year')},
        ),
        migrations.AddConstraint(
            model_name='schoolsetting',
            constraint=models.UniqueConstraint(fields=('school',), name='unique_school_setting_per_school'),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(fields=('school', 'admission_no'), name='unique_student_admission_per_school'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_profiles', to='core.school'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(bootstrap_default_school, migrations.RunPython.noop),
    ]
