# Generated by Django 5.2.11 on 2026-04-20 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_school_userprofile_alter_student_admission_no_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplateSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(choices=[('hall-ticket', 'Hall Ticket')], max_length=40)),
                ('accent_color', models.CharField(default='#cb0804', max_length=7)),
                ('logo_position', models.CharField(choices=[('both', 'Both'), ('left', 'Left'), ('right', 'Right'), ('center', 'Center')], default='both', max_length=10)),
                ('text_position', models.CharField(choices=[('center', 'Center'), ('left', 'Left'), ('right', 'Right')], default='center', max_length=10)),
                ('image_position', models.CharField(choices=[('right', 'Right'), ('left', 'Left'), ('top', 'Top'), ('bottom', 'Bottom')], default='right', max_length=10)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.school')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('school', 'document_type'), name='unique_document_template_setting_per_school')],
            },
        ),
    ]
