# Generated by Django 5.2.11 on 2026-04-20 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_documenttemplatesetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttemplatesetting',
            name='background_color',
            field=models.CharField(default='#f5fcc8', max_length=7),
        ),
        migrations.AddField(
            model_name='documenttemplatesetting',
            name='custom_logo',
            field=models.ImageField(blank=True, null=True, upload_to='document_templates/logos/'),
        ),
        migrations.AddField(
            model_name='documenttemplatesetting',
            name='text_color',
            field=models.CharField(default='#000080', max_length=7),
        ),
    ]
