# Generated by Django 5.2.11 on 2026-04-21 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_documenttemplatesetting_background_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttemplatesetting',
            name='text_font_size',
            field=models.PositiveSmallIntegerField(default=18),
        ),
        migrations.AddField(
            model_name='documenttemplatesetting',
            name='title_font_size',
            field=models.PositiveSmallIntegerField(default=38),
        ),
    ]
