# Generated by Django 5.2.11 on 2026-04-21 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_documenttemplatesetting_title_font_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttemplatesetting',
            name='custom_signature',
            field=models.ImageField(blank=True, null=True, upload_to='document_templates/signatures/'),
        ),
    ]
