# Generated by Django 5.2.13 on 2026-04-30 08:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_subscriptionpayment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documenttemplatesetting",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("id-card", "ID Card"),
                    ("bonafide", "Bonafide"),
                    ("hall-ticket", "Hall Ticket"),
                ],
                max_length=40,
            ),
        ),
        migrations.CreateModel(
            name="FeeReceipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("receipt_no", models.CharField(max_length=30)),
                (
                    "receipt_date",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ("tuition_fee", models.PositiveIntegerField(default=0)),
                ("library_fee", models.PositiveIntegerField(default=0)),
                ("lab_fee", models.PositiveIntegerField(default=0)),
                ("sports_fee", models.PositiveIntegerField(default=0)),
                ("other_fee", models.PositiveIntegerField(default=0)),
                (
                    "donation",
                    models.PositiveIntegerField(
                        default=0, help_text="Optional donation amount."
                    ),
                ),
                ("paid_amount", models.PositiveIntegerField(default=0)),
                ("remarks", models.CharField(blank=True, max_length=255)),
                (
                    "school",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="core.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fee_receipts",
                        to="core.student",
                    ),
                ),
            ],
            options={
                "ordering": ["-receipt_date", "-id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("school", "receipt_no"),
                        name="unique_fee_receipt_no_per_school",
                    )
                ],
            },
        ),
    ]
