# Generated by Django 5.2.13 on 2026-04-30 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_schoolrole"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="is_school_admin",
            field=models.BooleanField(default=True),
        ),
    ]
