# Generated by Django 5.2.13 on 2026-05-04 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_userprofile_is_school_admin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documenttemplatesetting",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("id-card", "ID Card"),
                    ("bonafide", "Bonafide"),
                    ("nirgam", "Nirgam"),
                    ("hall-ticket", "Hall Ticket"),
                    ("report-card", "Report Card"),
                ],
                max_length=40,
            ),
        ),
    ]
