# Generated by Django 5.2.4 on 2026-03-10 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_student_birth_place_student_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='caste',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='religion',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
